name: Deploy Eleventy via SSH

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*'] # Use the latest LTS Node.js

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install

      - run: npx @11ty/eleventy --output static

      # Test connectivity using netcat (nc)
      - name: Test connectivity to server (port 22)
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat
          nc -zv ${{ secrets.REMOTE_HOST }} 22

      # Test SSH connection using the provided key
      - name: Test SSH connection
        run: |
          # Write the SSH key to a temporary file
          echo "${{ secrets.SSH_KEY }}" > private_key
          chmod 600 private_key
          # Try connecting via SSH; disable strict host key checking to avoid prompts
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "echo 'SSH connection successful'"
      
      # Proceed with file copy if the tests succeed
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}  # Only needed if your key has a passphrase
          rm: true
          source: "static/"
          target: "${{ secrets.REMOTE_DIR }}"
