name: Deploy Eleventy via SSH

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*'] # Use latest LTS Node.js

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npx @11ty/eleventy --output static

      - name: Test SSH Connection (Detailed)
        run: |
          ssh-keyscan ${{ secrets.REMOTE_HOST }} >> known_hosts
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > private_key.pem # Remove CRLF (just in case)
          chmod 600 private_key.pem
          # Convert to OpenSSH format (if needed)
          if [[ $(head -n 1 private_key.pem | grep "BEGIN RSA PRIVATE KEY") ]]; then # Check if it's an RSA key
            ssh-keygen -p -m PEM -f private_key.pem > private_key_openssh.pem
            mv private_key_openssh.pem private_key.pem
          fi
          ssh -o StrictHostKeyChecking=no -o ForwardAgent=no -o UserKnownHostsFile=/dev/null -i private_key.pem ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'echo "SSH connection test successful!"'
          rm private_key.pem

      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }} # Only if your key has a passphrase
          rm: true
          source: "static/"
          target: "${{ secrets.REMOTE_DIR }}"